# Config file for automatic testing at travis-ci.org

language: python

env:
    - PY=''
    - PY=3


before_script:
  # Deactivate the virtualenv to get fast install of dependencies
  - deactivate
  # add ppa with more recent scipy version
  - sudo add-apt-repository ppa:rethinkdb/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install -qq python$PY-sphinx python$PY-nose python$PY-numpy python$PY-scipy

script:
  - python$PY setup.py install --user
  - python$PY run_tests.py
  - cd documentation/sphinx
  - make html