# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7_with_system_site_packages"
  - "3.2_with_system_site_packages"

before_script:
  # add ppa with more recent scipy version
  - sudo add-apt-repository ppa:pylab/stable  -y
  - sudo apt-get update -qq
  - sudo apt-get install -y python-sphinx python-nose python-numpy python-scipy
  - sudo apt-get install -y python3-sphinx python3-nose python3-numpy python3-scipy

script:
  - python setup.py install --user
  - python run_tests.py
  - cd documentation/sphinx
  - make html